### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by Mega-Bits** [Pfuenzle/anime-loads#20]
Bekomme beim starten des Container (Selbst gebuildet) folgenden Fehler:
```python
Traceback (most recent call last):
  File "/usr/src/app/./anibot.py", line 827, in <module>
    startbot()
  File "/usr/src/app/./anibot.py", line 608, in startbot
    al = animeloads(browser=browser, browserloc=browserlocation)
  File "/usr/src/app/animeloads.py", line 61, in __init__
    driver = webdriver.Firefox(service_log_path=os.devnull, options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 175, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 101, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 113, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64
```

Start Befehl (Nicht Entrypoint) ist:
`python ./anibot.py --configfile ./config/ani.json --docker`

ani.json lief mit der vorherigen Version ohne Probleme.

MFG

**Comment by Pfuenzle** [comment]
ist drin, das neue Dockerimage ist auch oben
