### ISSUE TITLE
downloader.py SSL Version Error

### ISSUE THREAD

**Issue by AlmightyLks** [Pfuenzle/anime-loads#29]
Verlauf + Fehlermeldung:

```
PS C:\Users\User\Downloads\anime-loads-1.7.2> python .\downloader.py
Starte interaktiven Modus

DevTools listening on ws://127.0.0.1:28845/devtools/browser/a04c2479-81a0-49b9-b75a-5a8725097ddc
[0603/000604.914:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0603/000604.914:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
Möchtest du dich anmelden? [J/N]: N
Überspringe Anmeldung
Angemeldet als Nutzer anonymous, VIP: False
Erfolgreich eingeloggt
Möchtest du deine Einstellungen ändern? [J/N]: N
Nach welchem Anime möchtst du suchen? (Du kannst jederzeit "suche" eingeben, um zurück zur Suche zu kommen oder "exit", um das Programm zu beenden): one piece
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.anime-loads.org', port=443): Max retries exceeded with url: /search?q=one%20piece (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\anime-loads-1.7.2\downloader.py", line 685, in <module>
    interactive()
  File "C:\Users\User\Downloads\anime-loads-1.7.2\downloader.py", line 284, in interactive
    results = al.search(aniquery)
  File "C:\Users\User\Downloads\anime-loads-1.7.2\animeloads.py", line 76, in search
    searchdata = self.session.get(apihelper.getSearchURL(query), allow_redirects=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.anime-loads.org', port=443): Max retries exceeded with url: /search?q=one%20piece (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))
```

**Comment by Pfuenzle** [comment]
Hey, sorry this took so long.
Do you still have this issue? I have never seen this error in this context

**Comment by AlmightyLks** [comment]
Eh, well.
I cancelled my crunchyroll sub, so I couldn't even re-create this if I wanted to
